version: '3.4'

name: "SeaBattle"
#networks:
#  app-tier:
#    driver: bridge

services:
  seabattle-gameresources-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: seabattle-gameresources-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55w0rd2022"
      MSSQL_PID: Express
    ports:
      - "1434:1433"
    #networks:
    #  - app-tier
    
  seabattle-gameresources-api:
    build:
      context: .
      dockerfile: SeaBattle.GameResources/Dockerfile
    container_name: seabattle-gameresources-api
    env_file: 
      - ./.env
    environment:
      DBServer: "seabattle-gameresources-db"
      DBPort: "1433"
      DBUser: "SA"
      DBPassword: "Pa55w0rd2022"
      Datbase: "SeaBattle.GameResources"
    ports:
      - "40078:40078"
      - "44359:44359"
    depends_on:
      - seabattle-gameresources-db
    #networks:
    #  - app-tier
  
  seabattle-authorizationservice-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: seabattle-authorizationservice-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa66w0rd2022"
      MSSQL_PID: Express
    ports:
      - "1435:1433"
    #networks:
    #  - app-tier
    
  seabattle-authorizationservice-api:
    build:
      context: .
      dockerfile: SeaBattle.AuthorizationService/Dockerfile
    container_name: seabattle-authorizationservice-api
    env_file: 
      - ./.env
    environment:
      DBServer: "seabattle-authorizationservice-db"
      DBPort: "1433"
      DBUser: "SA"
      DBPassword: "Pa66w0rd2022"
      Datbase: "SeaBattle.AuthorizationService"
    ports:
      - "44715:44715"
      - "44367:44367"
    depends_on:
      - seabattle-authorizationservice-db
    #networks:
    #  - app-tier

  seabattle-ui-client:
    build:
      context: .
      dockerfile: SeaBattle.UI_SPA/Dockerfile
    container_name: seabattle-ui-client
    ports:
      - "44716:44716"
      - "44391:44391"
    #networks:
    #  - app-tier

