version: '3.4'

name: "SeaBattle"

services:
  seabattle-gameresources-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: seabattle-gameresources-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55w0rd2022"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    
  seabattle-gameresources-api:
    build:
      context: .
      dockerfile: SeaBattle.GameResources/Dockerfile
    container_name: seabattle-gameresources-api
    environment:
      DBServer: "seabattle-gameresources-db"
      DBPort: "1433"
      DBUser: "SA"
      DBPassword: "Pa55w0rd2022"
      Datbase: "SeaBattle.GameResources"
    ports:
      - "40078:80"
      - "44359:443"
    depends_on:
      - seabattle-gameresources-db
  
  