// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeaBattle.Lib.Data.Entities;

namespace SeaBattle.GameResources.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20220216112118_DropPrimaryKey")]
    partial class DropPrimaryKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SeaBattle.Lib.Entities.BasicRepair", b =>
                {
                    b.Property<int>("NewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RepairPower")
                        .HasColumnType("int");

                    b.Property<int>("RepairRange")
                        .HasColumnType("int");

                    b.HasKey("NewId");

                    b.ToTable("Repairs");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.BasicWeapon", b =>
                {
                    b.Property<int>("NewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttackRange")
                        .HasColumnType("int");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.HasKey("NewId");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.Game", b =>
                {
                    b.Property<int>("NewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CurrentGamePlayerMove")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<byte>("MaxNumberOfPlayers")
                        .HasColumnType("tinyint");

                    b.Property<string>("Winner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NewId");

                    b.HasIndex("GameStateId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.GameField", b =>
                {
                    b.Property<int>("NewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("SizeX")
                        .HasColumnType("int");

                    b.Property<int>("SizeY")
                        .HasColumnType("int");

                    b.HasKey("NewId");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("GameFields");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.GameFieldCell", b =>
                {
                    b.Property<int>("NewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameFieldId")
                        .HasColumnType("int");

                    b.Property<int>("GameShipId")
                        .HasColumnType("int");

                    b.Property<bool>("Stern")
                        .HasColumnType("bit");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("NewId");

                    b.HasIndex("GameFieldId");

                    b.HasIndex("GameShipId");

                    b.ToTable("GameFieldCells");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.GamePlayer", b =>
                {
                    b.Property<int>("NewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PlayerStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("NewId");

                    b.HasIndex("Name");

                    b.HasIndex("PlayerStateId");

                    b.ToTable("GamePlayers");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.GameShip", b =>
                {
                    b.Property<int>("NewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GamePlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Hp")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.Property<int?>("StartFieldId")
                        .HasColumnType("int");

                    b.HasKey("NewId");

                    b.HasIndex("GamePlayerId");

                    b.HasIndex("ShipId");

                    b.HasIndex("StartFieldId");

                    b.ToTable("GameShips");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.GameState", b =>
                {
                    b.Property<int>("NewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NewId");

                    b.ToTable("GameStates");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.PlayerState", b =>
                {
                    b.Property<int>("NewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NewId");

                    b.ToTable("PlayerStates");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.Ship", b =>
                {
                    b.Property<int>("NewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Cost")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxHp")
                        .HasColumnType("int");

                    b.Property<int>("ShipTypeId")
                        .HasColumnType("int");

                    b.Property<byte>("Size")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Speed")
                        .HasColumnType("tinyint");

                    b.HasKey("NewId");

                    b.HasIndex("ShipTypeId");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.ShipType", b =>
                {
                    b.Property<int>("NewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NewId");

                    b.ToTable("ShipTypes");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.StartField", b =>
                {
                    b.Property<int>("NewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameFieldId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GamePlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("NewId");

                    b.HasIndex("GameFieldId");

                    b.HasIndex("GameId");

                    b.HasIndex("GamePlayerId");

                    b.ToTable("StartFields");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.StartFieldCell", b =>
                {
                    b.Property<int>("NewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GameShipNewId")
                        .HasColumnType("int");

                    b.Property<int>("StartFieldId")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("NewId");

                    b.HasIndex("GameShipNewId");

                    b.HasIndex("StartFieldId");

                    b.ToTable("StartFieldCells");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.Game", b =>
                {
                    b.HasOne("SeaBattle.Lib.Entities.GameState", "GameState")
                        .WithMany("Games")
                        .HasForeignKey("GameStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameState");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.GameField", b =>
                {
                    b.HasOne("SeaBattle.Lib.Entities.Game", "Game")
                        .WithOne("GameField")
                        .HasForeignKey("SeaBattle.Lib.Entities.GameField", "GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.GameFieldCell", b =>
                {
                    b.HasOne("SeaBattle.Lib.Entities.GameField", "GameField")
                        .WithMany("GameFieldCells")
                        .HasForeignKey("GameFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeaBattle.Lib.Entities.GameShip", "GameShip")
                        .WithMany("GameFieldCells")
                        .HasForeignKey("GameShipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameField");

                    b.Navigation("GameShip");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.GamePlayer", b =>
                {
                    b.HasOne("SeaBattle.Lib.Entities.PlayerState", "PlayerState")
                        .WithMany("GamePlayers")
                        .HasForeignKey("PlayerStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerState");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.GameShip", b =>
                {
                    b.HasOne("SeaBattle.Lib.Entities.GamePlayer", "GamePlayer")
                        .WithMany("GameShips")
                        .HasForeignKey("GamePlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeaBattle.Lib.Entities.Ship", "Ship")
                        .WithMany("GameShips")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeaBattle.Lib.Entities.StartField", "StartField")
                        .WithMany("GameShips")
                        .HasForeignKey("StartFieldId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GamePlayer");

                    b.Navigation("Ship");

                    b.Navigation("StartField");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.Ship", b =>
                {
                    b.HasOne("SeaBattle.Lib.Entities.ShipType", "ShipType")
                        .WithMany("Ships")
                        .HasForeignKey("ShipTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipType");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.StartField", b =>
                {
                    b.HasOne("SeaBattle.Lib.Entities.GameField", "GameField")
                        .WithMany("StartFields")
                        .HasForeignKey("GameFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeaBattle.Lib.Entities.Game", "Game")
                        .WithMany("StartFields")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeaBattle.Lib.Entities.GamePlayer", "GamePlayer")
                        .WithMany("StartFields")
                        .HasForeignKey("GamePlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("GameField");

                    b.Navigation("GamePlayer");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.StartFieldCell", b =>
                {
                    b.HasOne("SeaBattle.Lib.Entities.GameShip", null)
                        .WithMany("StartFieldCells")
                        .HasForeignKey("GameShipNewId");

                    b.HasOne("SeaBattle.Lib.Entities.StartField", "StartField")
                        .WithMany("StartFieldCells")
                        .HasForeignKey("StartFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StartField");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.Game", b =>
                {
                    b.Navigation("GameField");

                    b.Navigation("StartFields");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.GameField", b =>
                {
                    b.Navigation("GameFieldCells");

                    b.Navigation("StartFields");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.GamePlayer", b =>
                {
                    b.Navigation("GameShips");

                    b.Navigation("StartFields");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.GameShip", b =>
                {
                    b.Navigation("GameFieldCells");

                    b.Navigation("StartFieldCells");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.GameState", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.PlayerState", b =>
                {
                    b.Navigation("GamePlayers");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.Ship", b =>
                {
                    b.Navigation("GameShips");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.ShipType", b =>
                {
                    b.Navigation("Ships");
                });

            modelBuilder.Entity("SeaBattle.Lib.Entities.StartField", b =>
                {
                    b.Navigation("GameShips");

                    b.Navigation("StartFieldCells");
                });
#pragma warning restore 612, 618
        }
    }
}
