//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaBattle.UIConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeaBattle.UIConsole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action phase.
        /// </summary>
        internal static string ActionPhase {
            get {
                return ResourceManager.GetString("ActionPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        internal static string Attack {
            get {
                return ResourceManager.GetString("Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy ship.
        /// </summary>
        internal static string BuyShip {
            get {
                return ResourceManager.GetString("BuyShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose action.
        /// </summary>
        internal static string ChooseAction {
            get {
                return ResourceManager.GetString("ChooseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose direction.
        /// </summary>
        internal static string ChooseDirection {
            get {
                return ResourceManager.GetString("ChooseDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose ship or buy.
        /// </summary>
        internal static string ChooseOrBuyShip {
            get {
                return ResourceManager.GetString("ChooseOrBuyShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose ship for removing.
        /// </summary>
        internal static string ChooseShipForRemove {
            get {
                return ResourceManager.GetString("ChooseShipForRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cost.
        /// </summary>
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of players should be equal to or less than.
        /// </summary>
        internal static string ExceededMaxNumberOfPlayers {
            get {
                return ResourceManager.GetString("ExceededMaxNumberOfPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game field already created or no game yet..
        /// </summary>
        internal static string GameFieldCrOrNoGame {
            get {
                return ResourceManager.GetString("GameFieldCrOrNoGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game was finished..
        /// </summary>
        internal static string GameFinished {
            get {
                return ResourceManager.GetString("GameFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game already created..
        /// </summary>
        internal static string GameReadCr {
            get {
                return ResourceManager.GetString("GameReadCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hp.
        /// </summary>
        internal static string Hp {
            get {
                return ResourceManager.GetString("Hp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input name for player.
        /// </summary>
        internal static string InpNamePlayers {
            get {
                return ResourceManager.GetString("InpNamePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input number of players..
        /// </summary>
        internal static string InpNumPlayers {
            get {
                return ResourceManager.GetString("InpNumPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input sizeX.
        /// </summary>
        internal static string InputSizeX {
            get {
                return ResourceManager.GetString("InputSizeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input sizeY.
        /// </summary>
        internal static string InputSizeY {
            get {
                return ResourceManager.GetString("InputSizeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong input. You should repeat..
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation..
        /// </summary>
        internal static string InvalidOperation {
            get {
                return ResourceManager.GetString("InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong player..
        /// </summary>
        internal static string InvalidPlayer {
            get {
                return ResourceManager.GetString("InvalidPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong position for ship..
        /// </summary>
        internal static string InvalidPositionShip {
            get {
                return ResourceManager.GetString("InvalidPositionShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong ship..
        /// </summary>
        internal static string InvalidShip {
            get {
                return ResourceManager.GetString("InvalidShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max hp.
        /// </summary>
        internal static string MaxHp {
            get {
                return ResourceManager.GetString("MaxHp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action on target was missed..
        /// </summary>
        internal static string MissTarget {
            get {
                return ResourceManager.GetString("MissTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement phase.
        /// </summary>
        internal static string MovementPhase {
            get {
                return ResourceManager.GetString("MovementPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target is out of distance..
        /// </summary>
        internal static string OutOfDistance {
            get {
                return ResourceManager.GetString("OutOfDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough points..
        /// </summary>
        internal static string PointsShortage {
            get {
                return ResourceManager.GetString("PointsShortage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press button.
        /// </summary>
        internal static string PressButton {
            get {
                return ResourceManager.GetString("PressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove ship from field.
        /// </summary>
        internal static string RemoveShipFromField {
            get {
                return ResourceManager.GetString("RemoveShipFromField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repair.
        /// </summary>
        internal static string RepairLCase {
            get {
                return ResourceManager.GetString("RepairLCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repairs.
        /// </summary>
        internal static string Repairs {
            get {
                return ResourceManager.GetString("Repairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        internal static string RepairUCase {
            get {
                return ResourceManager.GetString("RepairUCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select new place for ship.
        /// </summary>
        internal static string SelectPlaceShip {
            get {
                return ResourceManager.GetString("SelectPlaceShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select position of the ship&apos;s stern.
        /// </summary>
        internal static string SelectPosShipStern {
            get {
                return ResourceManager.GetString("SelectPosShipStern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ship.
        /// </summary>
        internal static string SelectShip {
            get {
                return ResourceManager.GetString("SelectShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ship for attack.
        /// </summary>
        internal static string SelectShipAttack {
            get {
                return ResourceManager.GetString("SelectShipAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ship for repair.
        /// </summary>
        internal static string SelectShipRepair {
            get {
                return ResourceManager.GetString("SelectShipRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell ship.
        /// </summary>
        internal static string SellShip {
            get {
                return ResourceManager.GetString("SellShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set ship on the field.
        /// </summary>
        internal static string SetShipField {
            get {
                return ResourceManager.GetString("SetShipField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship.
        /// </summary>
        internal static string Ship {
            get {
                return ResourceManager.GetString("Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size X should be between.
        /// </summary>
        internal static string SizeXBetween {
            get {
                return ResourceManager.GetString("SizeXBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Y should be between.
        /// </summary>
        internal static string SizeYBetween {
            get {
                return ResourceManager.GetString("SizeYBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error.
        /// </summary>
        internal static string SomeError {
            get {
                return ResourceManager.GetString("SomeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speed.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target was destroyed..
        /// </summary>
        internal static string TargetDestroyed {
            get {
                return ResourceManager.GetString("TargetDestroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weapon.
        /// </summary>
        internal static string Weapon {
            get {
                return ResourceManager.GetString("Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weapons.
        /// </summary>
        internal static string Weapons {
            get {
                return ResourceManager.GetString("Weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner.
        /// </summary>
        internal static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
    }
}
